// DOM Elements:
const letterEl = document.querySelector(".letter-and-multiplier p")
const letterContainerEl = document.querySelector(".letter")
const btnThemeSwitchEl = document.querySelector(".theme-switcher")
const scoreMultiplierBarEl = document.querySelector(".score-multiplier")
const leftIndicatorEl = document.querySelector(".indicator.left")
const rightIndicatorEl = document.querySelector(".indicator.right")
const scoreSpanEl = document.querySelector(".scores span")
const lettersRemainingSpanEl = document.querySelector(".letters-remaining span")
const nextLetterSpanEl = document.querySelector(".next-letter span")
const currentStreakSpanEl = document.querySelector(".current-streak span")
const maxStreakSpanEl = document.querySelector(".max-streak span")
const accuracySpanEl = document.querySelector(".accuracy span")
const appContainerEl = document.querySelector(".container")
